name: CodeGuru Reviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    # * is a special character in YAML so you have to quote this stringa
    - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  test:

    runs-on: ubuntu-latest

   # Step 1 Add checkouts to your workflow.yml file
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # Extra step requied for Private Beta
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      if: ${{ always() }}
      with:
        repository: vijejain/cicd-actions-bugbash
        ref: refs/heads/main
        token: ${{ secrets.TOKEN }}
        path: ./.github/vijejain/cicd-actions-bugbash

   # Step 2 Provide your AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # Step 3 Add CodeGuru Reviewer Action
    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions-bugbash
      if: ${{ success() }}
      with:          
        s3_bucket: codeguru-reviewer-234
        
    # Step 4 Upload results    
    - name: Upload review result
      if: ${{ success() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json 
