# This workflow will build a 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
#Add Python build scripts

    # Extra step requied for BugBash
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      if: ${{ always() }}
      with:
        repository: vijejain/cicd-actions-bugbash
        ref: refs/heads/main
        token: ${{ secrets.TOKEN }}
        path: ./.github/vijejain/cicd-actions-bugbash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    # Edited for BugBashdd
    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions-bugbash
      if: ${{ success() }}
      with:          
        s3_bucket: codeguru-reviewer-mybucket-234
        
    - name: Upload review result
      if: ${{ success() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json 
        
      
